### ISSUE TITLE
The bot insults himself when added to a group

### ISSUE THREAD

**Issue by rnestler** [coredump-ch/flamebot#14]
It was hilarious :smile: 
![2015-12-10 10_22_09-telegram web - vimperator](https://cloud.githubusercontent.com/assets/1435346/11711627/156d7f36-9f28-11e5-9534-6e26974d3892.png)

**Comment by dbrgn** [comment]
Ahaha :joy:

**Comment by netzhuffle** [comment]
Is this a feature or a bug? ;)

**Comment by dbrgn** [comment]
@rnestler and I agree that this is a feature :smile:
