### ISSUE TITLE
How do I use it?

### ISSUE THREAD

**Issue by The-Compiler** [coredump-ch/flamebot#22]
So after the lightning talks today I tried using the bot.

However, when messaging it directly, nothing happens. I also couldn't find a way to invite it in a group channel, so I `@mentioned` it there, and nothing happened either.

How can I get insulted? :wink:

**Comment by The-Compiler** [comment]
Okay, I found a button to invite a member on Telegram Desktop, no idea why I don't see it on mobile...

Still would be nice if directly chatting with it would make it respond too.

**Comment by rnestler** [comment]
I'm not sure if it can detect direct chatting yet. PRs welcome :smiley:

**Comment by netzhuffle** [comment]
Currently on direct chatting it has the same 2 % reply possibility like in group chats. You can trigger a 100 % reply when mentioning its name (`@CoredumpFlameBot`) in the message or using a German monkey island insult. But like @rnestler said, feel free to do a PR to change the probability to 100 % in direct chats!
