### ISSUE TITLE
Dini Mueter isch muetig!

### ISSUE THREAD

**Issue by The-Compiler** [coredump-ch/flamebot#25]
```
<Marco> Gseht muetig us xD
<FlameBot> HANI MUETTER GHÖRT??!
```

err, nope :wink:

**Comment by mzollin** [comment]
close enough though...

**Comment by rnestler** [comment]
Er frögt ja höflich nach ob er Dich richtig verstande het ;)

**Comment by rnestler** [comment]
D regex isch da: https://github.com/coredump-ch/telegram-flame-bot/blob/master/FlameBot.js#L108
`/mue?tt?(er|i)/`

Ich glaub si `i` isch für `mutti` und `mueti`. Muetig beinhaltet halt Mueti und somit isch d Frag vom Bot völlig berechtigt 😉

**Comment by The-Compiler** [comment]
ja denn, works as designed? :laughing:

**Comment by mzollin** [comment]
"muti" triggered aber au schinbar :)
