### ISSUE TITLE
Kaputt?

### ISSUE THREAD

**Issue by The-Compiler** [coredump-ch/flamebot#27]
Since yesterday (or so), the flamebot doesn't react to anything anymore - did something break?

**Comment by dbrgn** [comment]
We updated the server some time ago. @netzhuffle can you check whether the process could be started again?

Maybe you can add a cronjob every 10 minutes that starts the bot again if it died?

**Comment by netzhuffle** [comment]
Restarted the bots by hand. I’m looking into an automatic starting solution.

**Comment by rnestler** [comment]
> Restarted the bots by hand. I’m looking into an automatic starting solution.

was the bot hung or did it just stop? If it stopped we could probably do something with a systemd unit which restarts automatically.

**Comment by dbrgn** [comment]
Yeah, we could also add a systemd unit and add the restart command to the sudoers file.

**Comment by dbrgn** [comment]
@netzhuffle FYI, restarted the server again (kernel security bugfixes).

If you give me a Systemd unit file (it's not hard to write them), I can install it on the server and give you the permissions to restart the service.

**Comment by The-Compiler** [comment]
Seems to be broken again. 😢

**Comment by The-Compiler** [comment]
Aaaand again (or is someone just restarting it to apply the latest updates? :wink:)

**Comment by netzhuffle** [comment]
@dbrgn Like

```
[Unit]
Description=Telegram Flame Bot, https://github.com/coredump-ch/telegram-flame-bot/

[Service]
Type=forking
User=jannis
Group=jannis
WorkingDirectory=-
ExecStart=node_modules/forever/bin/forever -c bin/node -l telegram-flame-bot/forever.log -o telegram-flame-bot/out.log -e telegram-flame-bot/error.log telegram-flame-bot/bot.js
```

?

**Comment by dbrgn** [comment]
@netzhuffle thanks! Sorry for the long delay. Some comments:

You don't need `forever` since that's exactly what systemd does for you:

```ini
[Service]
Type=simple
ExecStart=/home/jannis/bin/node telegram-flame-bot/bot.js
Restart=always
```

The working directory should be the user home.

```ini
[Service]
WorkingDirectory=~
```

You want to make sure that the flamebot is started after the network is up:

```ini
[Unit]
Description=Telegram Flame Bot
Wants=network-online.target
After=network-online.target
```

You also want to start the service on boot:

```ini
[Install]
WantedBy=multi-user.target
```

Because systemd is not just shitty as some people think, there are some useful options to limit the power of services. First, let's ensure that the process does not go haywire with regards to memory:

```ini
[Service]
MemoryLimit=512M
```

Then avoid making more things readable than necessary:

```ini
[Service]
InaccessibleDirectories=/var /srv
ReadOnlyDirectories=/
ReadWriteDirectories=/home/jannis
```

Resulting unit file:

```ini
[Unit]
Description=Telegram Flame Bot
Wants=network-online.target
After=network-online.target

[Service]
Type=simple
User=jannis
Group=jannis
WorkingDirectory=~
ExecStart=/home/jannis/bin/node telegram-flame-bot/bot.js
Restart=always
MemoryLimit=512M
InaccessibleDirectories=/var /srv
ReadOnlyDirectories=/
ReadWriteDirectories=/home/jannis

[Install]
WantedBy=multi-user.target
```

**Comment by dbrgn** [comment]
@netzhuffle I deployed this with a sudoers file that allows you to run the following commands:

    sudo systemctl restart flamebot

To see logs:

    sudo journalctl -u flamebot

To follow logs:

    sudo journalctl -f -u flamebot

Does that work for you?

**Comment by netzhuffle** [comment]
@dbrgn Works perfectly, thank you very much!
