### ISSUE TITLE
Upgrade version running on server?

### ISSUE THREAD

**Issue by The-Compiler** [coredump-ch/flamebot#32]
Whoever runs `@CoredumpFlameBot` seems to be running an older version - it still [can't do cyber](https://github.com/coredump-ch/telegram-flame-bot/pull/29), and also still seems to have the typos fixed in 3a80e80047eccf09c6cdfd92a1a596dea0952e48 (November 2017).

Any chance that could be upgraded? :wink:

**Comment by dbrgn** [comment]
That would be @netzhuffle :slightly_smiling_face:

**Comment by The-Compiler** [comment]
Looks like this happened in the meantime - thanks!

**Comment by dbrgn** [comment]
Currently we deploy using Ansible, but we could also set up something like Watchtower to auto-deploy when new images are pushed to Dockerhub.
