### ISSUE TITLE
Update nodejs version

### ISSUE THREAD

**Issue by rnestler** [coredump-ch/flamebot#46]
We currently run with node 10 it seems which is no longer supported.

**Comment by dbrgn** [comment]
Yeah, 16 and 18 are current 😄

**Comment by rnestler** [comment]
We don't even pin the node version for the project itself, only for CI and the Docker container, so probably it just works with newer node versions

**Comment by rnestler** [comment]
We fixed this in https://github.com/coredump-ch/flamebot/pull/49
